name: ClusterFuzzLite continuous builds

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  build:
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/clusterfuzzlite-shared.yml
    secrets: inherit
    with:
      job_name: Continuous build
      run_fuzzers: false
      upload_build: true
